MainPath = 'G:\\My Drive'
OldMainPath = "C:\\Users\\hyacinthe\\Desktop"

OrderBookPath = MainPath + '\\databases\\OrderBook.csv'
PositionsPath = MainPath + '\\databases\\Positions.csv'
CashAccountPath = MainPath + '\\databases\\CashAccount.csv'
PnLPath = MainPath + '\\databases\\PnL.csv'
SecuritiesPath = MainPath + '\\databases\\Securities.csv'
QuotesPath = MainPath + '\\databases\\Quotes\\'
StrategiesPath = MainPath + '\\databases\\Strategies\\'
BacktestResultsPath = MainPath + '\\strategies\\backtest\\results\\'
StudyResultsPath = MainPath + '\\strategies\\studies\\results\\'
UATResultsPath = MainPath + '\\strategies\\uat\\results\\'
ToBookPath = MainPath + '\\strategies\\prod\\'
Tokens = MainPath + '\\databases\\tokens.json'
